/**
 * Generates public/sitemap.xml from the route manifest below.
 *
 * Runs automatically as part of `pnpm build` (see package.json), so the
 * sitemap can't silently drift out of date the way the hand-maintained one
 * did — it was missing 10 public pages and pointed every URL at the wrong
 * domain.
 *
 * Adding a public page? Add it to PUBLIC_ROUTES. Anything not listed here
 * simply won't be submitted to search engines.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT_PATH = path.resolve(__dirname, "../public/sitemap.xml")

// Keep in sync with src/lib/site.ts. Duplicated deliberately: this script runs
// in plain Node before the Vite build, so it can't import a module that relies
// on import.meta.env.
const SITE_URL = (process.env.VITE_SITE_URL ?? "https://genxqr.com").replace(/\/$/, "")

/**
 * priority is relative within this site only — it does not affect ranking.
 * changefreq is a hint, not a directive. Both are advisory; `loc` is what
 * actually matters.
 */
const PUBLIC_ROUTES = [
  // Core
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/features", changefreq: "monthly", priority: "0.9" },
  { path: "/pricing", changefreq: "monthly", priority: "0.9" },
  { path: "/dynamic-qr", changefreq: "monthly", priority: "0.9" },
  { path: "/use-cases", changefreq: "monthly", priority: "0.8" },

  // Free tools — high intent, worth crawling often
  { path: "/generate", changefreq: "monthly", priority: "0.9" },
  { path: "/generate/url", changefreq: "monthly", priority: "0.8" },
  { path: "/generate/wifi", changefreq: "monthly", priority: "0.8" },
  { path: "/generate/whatsapp", changefreq: "monthly", priority: "0.8" },
  { path: "/generate/instagram", changefreq: "monthly", priority: "0.8" },
  { path: "/scanner", changefreq: "monthly", priority: "0.8" },

  // Content
  { path: "/blog", changefreq: "weekly", priority: "0.7" },
  { path: "/faq", changefreq: "monthly", priority: "0.7" },
  { path: "/api-docs", changefreq: "monthly", priority: "0.8" },
  { path: "/about", changefreq: "monthly", priority: "0.6" },
  { path: "/contact", changefreq: "yearly", priority: "0.6" },
  { path: "/careers", changefreq: "weekly", priority: "0.5" },
  { path: "/changelog", changefreq: "weekly", priority: "0.5" },

  // Legal — low priority but should still be indexed for trust signals.
  // refund-policy and delivery-policy are also required to be publicly
  // reachable for Indian payment-gateway onboarding.
  { path: "/privacy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", changefreq: "yearly", priority: "0.3" },
  { path: "/refund-policy", changefreq: "yearly", priority: "0.4" },
  { path: "/delivery-policy", changefreq: "yearly", priority: "0.4" },
  { path: "/cookie-policy", changefreq: "yearly", priority: "0.3" },
  { path: "/gdpr", changefreq: "yearly", priority: "0.3" },
]

/**
 * Deliberately excluded, and why — kept here so the reasoning survives:
 *  /login, /signup, /forgot-password, /reset-password, /verify-email
 *      Auth screens: no content to rank, and indexing them invites confusion.
 *  /invite/:token, /r/:slug/*, /l/:slug
 *      Per-user or per-QR URLs. Indexing them would leak customer content
 *      into search results.
 *  /app/*, /admin/*
 *      Authenticated areas; also blocked in robots.txt.
 */

const today = new Date().toISOString().slice(0, 10)

const body = PUBLIC_ROUTES.map(
  (route) => `  <url>
    <loc>${SITE_URL}${route.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
).join("\n")

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

fs.writeFileSync(OUT_PATH, xml, "utf8")
console.log(`sitemap.xml — ${PUBLIC_ROUTES.length} URLs written for ${SITE_URL}`)
