/**
 * Generates public/sitemap.xml from the route manifest below.
 *
 * Runs automatically as part of `pnpm build` (see package.json), so the
 * sitemap can't silently drift out of date the way the hand-maintained one
 * did — it was missing 10 public pages and pointed every URL at the wrong
 * domain.
 *
 * Adding a public page? Add it to PUBLIC_ROUTES. Anything not listed here
 * simply won't be submitted to search engines.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
import { PUBLIC_ROUTES, SITE_URL } from "./public-routes.mjs"

const OUT_PATH = path.resolve(__dirname, "../public/sitemap.xml")

// The route manifest and SITE_URL live in public-routes.mjs, shared with
// prerender.mjs. They used to be defined here, which meant the sitemap could
// list a page the prerender step never rendered — submitting an empty document
// to Google — with nothing to make the mismatch visible.
const today = new Date().toISOString().slice(0, 10)

const body = PUBLIC_ROUTES.map(
  (route) => `  <url>
    <loc>${SITE_URL}${route.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
).join("\n")

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

fs.writeFileSync(OUT_PATH, xml, "utf8")
console.log(`sitemap.xml — ${PUBLIC_ROUTES.length} URLs written for ${SITE_URL}`)
