// GENERATED by scripts/build-frame-manifest.mjs — do not edit by hand.
// Source of truth is the SVG files in public/frames/. Run `pnpm frames:build`
// (or any `pnpm build`) after adding, removing or editing one.

export interface FrameTextSlot {
  x: number; y: number; w: number; h: number
  size: number; color: string; align: "start" | "center" | "end"
}

export interface FrameAssetEntry {
  id: string
  label: string
  category: string
  /** Public path, served straight from disk by nginx (see the *.svg location). */
  file: string
  w: number
  h: number
  /** Where the QR is composited. Always square; artwork never draws over it. */
  qr: { x: number; y: number; size: number }
  text?: FrameTextSlot
  /** Artwork uses currentColor, so the user's frame colour is substituted. */
  tintable: boolean
}

export const FRAME_ASSETS: FrameAssetEntry[] = [
  {
    "id": "birthday-balloons",
    "label": "Balloons",
    "category": "Birthday",
    "file": "/frames/birthday-balloons.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#7c3aed",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "christmas-pine",
    "label": "Pine &amp; Baubles",
    "category": "Christmas",
    "file": "/frames/christmas-pine.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#14532d",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "diwali-diyas",
    "label": "Diyas &amp; Rangoli",
    "category": "Diwali",
    "file": "/frames/diwali-diyas.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#fcd34d",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "easter-eggs",
    "label": "Easter Eggs",
    "category": "Easter",
    "file": "/frames/easter-eggs.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#7c6aa8",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "eid-crescent",
    "label": "Crescent &amp; Lanterns",
    "category": "Eid",
    "file": "/frames/eid-crescent.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 42,
      "color": "#fcd34d",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "food-menu-plate",
    "label": "Cutlery Menu",
    "category": "Food &amp; Menu",
    "file": "/frames/food-menu-plate.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 42,
      "color": "#ffffff",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "halloween-pumpkins",
    "label": "Pumpkins &amp; Bats",
    "category": "Halloween",
    "file": "/frames/halloween-pumpkins.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#fb923c",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "new-year-fireworks",
    "label": "Fireworks",
    "category": "New Year",
    "file": "/frames/new-year-fireworks.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#fcd34d",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "shopping-sale",
    "label": "Shopping",
    "category": "Shopping",
    "file": "/frames/shopping-sale.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#ffffff",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "standard-corner-accent",
    "label": "Corner Accent",
    "category": "Standard",
    "file": "/frames/standard-corner-accent.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 170,
      "y": 160,
      "size": 660
    },
    "text": {
      "x": 60,
      "y": 856,
      "w": 880,
      "h": 100,
      "size": 46,
      "color": "#ffffff",
      "align": "center"
    },
    "tintable": true
  },
  {
    "id": "standard-cta-bar",
    "label": "Bold CTA",
    "category": "Standard",
    "file": "/frames/standard-cta-bar.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 150,
      "y": 130,
      "size": 700
    },
    "text": {
      "x": 0,
      "y": 866,
      "w": 1000,
      "h": 134,
      "size": 52,
      "color": "#ffffff",
      "align": "center"
    },
    "tintable": true
  },
  {
    "id": "standard-gold-deco",
    "label": "Gold Deco",
    "category": "Standard",
    "file": "/frames/standard-gold-deco.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 848,
      "w": 880,
      "h": 100,
      "size": 42,
      "color": "#b08d3f",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "standard-phone",
    "label": "Phone Mockup",
    "category": "Standard",
    "file": "/frames/standard-phone.svg",
    "w": 1000,
    "h": 1180,
    "qr": {
      "x": 200,
      "y": 250,
      "size": 600
    },
    "text": {
      "x": 100,
      "y": 940,
      "w": 800,
      "h": 110,
      "size": 46,
      "color": "#ffffff",
      "align": "center"
    },
    "tintable": true
  },
  {
    "id": "thanksgiving-harvest",
    "label": "Autumn Leaves",
    "category": "Thanksgiving",
    "file": "/frames/thanksgiving-harvest.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#92400e",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "travel-plane",
    "label": "Travel",
    "category": "Travel",
    "file": "/frames/travel-plane.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#0e7490",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "valentines-hearts",
    "label": "Hearts",
    "category": "Valentine's Day",
    "file": "/frames/valentines-hearts.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 44,
      "color": "#be123c",
      "align": "center"
    },
    "tintable": false
  },
  {
    "id": "wedding-floral",
    "label": "Eucalyptus &amp; Blush",
    "category": "Wedding",
    "file": "/frames/wedding-floral.svg",
    "w": 1000,
    "h": 1000,
    "qr": {
      "x": 180,
      "y": 170,
      "size": 640
    },
    "text": {
      "x": 60,
      "y": 840,
      "w": 880,
      "h": 100,
      "size": 42,
      "color": "#7a6a55",
      "align": "center"
    },
    "tintable": false
  }
]
